app/Http/routes.php
<?php


Route::get('/', function () {
       return view('Auth.login');
   });


	//rutas para usuarios

Route::get('login','UsersController@showLoginForm');
Route::post('login','UsersController@authenticate');
Route::get('logout','UsersController@logout');
Route::get('register','UsersController@getRegister');
Route::post('register','UsersController@postRegister');
Route::get('usuario/create/{id}','UsersController@create');
Route::resource('usuario','UsersController');


Route::group(['middleware'=>['auth','admin_sistema']],function(){
	//ruta para los roles
	Route::resource('roles','RolesController');
    //rutas de usuarios q solo puede acceder el admin
	Route::get('user/{id}',['as'=>'usuario-eliminar','uses'=>'UsersController@mostrar']);
	Route::get('{id}/edit','UsersController@getEdit');
});

//ruta hacia home
Route::get('home', 'HomeController@index');
//rutas para proveedor
Route::get('proveedor/detail/{id}', 'Article\ProviderController@detail');
Route:: resource('proveedor','Article\ProviderController');
//rutas para departamento
Route::resource('departamento', 'Departamento\DepartmentController');
//rutas para especifico
Route::resource('especifico','EspecificoController');
Route::get('especifico/delete/{id}','EspecificoController@delete')->name('yes');
//rutas para unidad de medida
Route::resource('unidad','UnidadMedidaController');
Route::get('unidad/delete/{id_unidad_medida}','UnidadMedidaController@delete')->name('delete_unidad');
//rutas para articulo
Route::resource('articulo','ArticuloController');
Route::get('articulo/delete/{codigoArticulo}','ArticuloController@delete')->name('delete_articulo');
//rutas para ingreso
Route::resource('ingreso','IngresoController');
Route::get('ingreso/delete/{idIngreso}','IngresoController@delete')->name('delete_ingreso');

Route::get('ingreso/addExistencia/{codProducto}/{idPresentacion}','IngresoController@addExistencia')->name('addExistencia');

Route::resource('observacion','ObservacionController');
Route::get('observacion/delete/{idObservacion}','ObservacionController@delete')->name('delete_observacion');


Route::resource('existencia','ExistenciaController');

Route::resource('presentacion','PresentacionController');

//rutas para observacion
Route::resource('observacion','ObservacionController');
Route::get('observacion/delete/{idObservacion}','ObservacionController@delete')->name('delete_observacion');


//requisicion
//ver la requisicion que se esta creando
Route::get('requisicion/crear',[
		'as'=>'requisicion-show',
		'uses'=>'RequisicionController@crear'
	]);
//agregar articulo a la requisicion
Route::get('requisicion/add/{cod}/{cantidad}','RequisicionController@add');

//eliminar articulo de la requisicion
Route::get('requisicion/delete/{cod}',[
		'as'=>'requisicion-delete',
		'uses'=>'RequisicionController@delete'
	]);
//eliminar la requisicion que se esta creando
Route::get('requisicion/trash',[
		'as'=>'requisicion-trash',
		'uses'=>'RequisicionController@trash'
	]);
//actualizar cantidad en articulo de la requisicion
Route::get('requisicion/update/{cod}/{cantidad}','RequisicionController@update');
//almacenar la requisicion
Route::get('requisicion/store','RequisicionController@store');
Route::get('requisicion/listar',['as'=>'requisicion-listar','uses'=>'RequisicionController@index']);

// detalle requisicion
 //para todo el controlador
Route::resource('requisicion/detalle','DetalleRequisicionController');
//aprobar la requisicion (por el administrador financiero)
Route::get('requisicion/detalle/aprobar/{id}','DetalleRequisicionController@aprobar');
//imprimir requisicion
Route::get('requisicion/imprimir/{id}','DetalleRequisicionController@imprimir');
Route::get('requisicion/observacion/{id}',[
	'as'=>'requisicion-observacion',
	'uses'=>'DetalleRequisicionController@observacion'
	]);
//habilitar que los usuarios de departamento envien requisiciones
Route::get('habilitarEnvios',['as'=>'habilitar-envios','uses'=>'RequisicionController@HabilitarEnvio']);
Route::get('gestinarEnvios/{id}',['as'=>'gestionar-envios','uses'=>'RequisicionController@gestionarEnvios']);

app/Models/UnidadMedida.php
<?php

namespace sig\Models;

use Illuminate\Database\Eloquent\Model;
use sig\Models\Articulo;

class UnidadMedida extends Model
{
    protected $table = 'unidad_medida';
	protected $primaryKey = 'id_unidad_medida';
	
	protected $fillable = ['nombre_unidadmedida'];
	
	//Relacion uno a muchos con articulo
	public function articulo(){
		return $this->hasMany('sig\Models\Articulo','id_unidad_medida');
	}
}

app/Http/Controllers/UnidadMedidaController.php
<?php

namespace sig\Http\Controllers;

use Illuminate\Http\Request;

use sig\Http\Requests;
use DB;
use Session;
//importacion del modelo a usar con el ORM
use sig\Models\UnidadMedida;

class UnidadMedidaController extends Controller
{
	 public function __construct()
    {
        $this->middleware('auth');
    }
    
    public function index(){
		$unidades = UnidadMedida::orderBy('nombre_unidadmedida','asc')->get();		
		return view('unidadmedida.index',['unidades'=>$unidades]);
	}
	
	public function create()
    {
        return view('unidadmedida.create');
    }

    public function store(Request $request)
    {
        $this->validate($request,[
		    'nombre_unidadmedida' => 'required|regex: /^[a-zA-Zoueai0-9\/\s]*$/ |unique:unidad_medida,nombre_unidadmedida',			
		]);
		
		UnidadMedida::create([
		           'nombre_unidadmedida' =>$request->input('nombre_unidadmedida')
		           ]);
		flash('Unidad de medida guardada exitosamente','success');	   
		return redirect()->route('unidad.index');
	     
    }

    public function show($idUnidadMedida)
    {
       $unidad = UnidadMedida::findOrFail($idUnidadMedida);	   
	   return view('unidadmedida.details',['unidad'=>$unidad]);
	}    
 
    public function edit($idUnidadMedida)
	{
       $unidad = UnidadMedida::findOrFail($idUnidadMedida);
	   return view('unidadmedida.edit',['unidad'=>$unidad]); 
    }

    public function update(Request $request, $id)
    {
		//Valida que el nombre de la unidad de medida sea unica, exceptuando ella misma
        $this->validate($request,[
		   'nombre_unidadmedida'=>'required|regex: /^[a-zA-Zoueai0-9\/\s]*$/ |unique:unidad_medida,nombre_unidadmedida,'.$id.',id_unidad_medida'
		]);
		$unidad = UnidadMedida::FindOrFail($id);
		if($unidad){
			$unidad ->update([
			  'nombre_unidadmedida' => $request->input('nombre_unidadmedida')
			  ]);
	    flash('Unidad de medida actualizado exitosamente','success');
		return redirect()->route('unidad.index');			
		}else{
			flash('Error: no se pudo actualizar la unidad de medida','danger');
			return redirect()->route('unidad.index');
		}
				    
    }
    
	public function delete($idUnidadMedida){
			$unidad =UnidadMedida::findOrFail($idUnidadMedida);
			return view('unidadmedida.delete',['unidad'=>$unidad]);
		}
    
    public function destroy($idUnidadMedida)
    {
        $unidad = UnidadMedida::findOrFail($idUnidadMedida);
		//Comprueba que la unidad a eliminar no esta relacionado con ningun articulo
		if($unidad->articulo->count()>0){			
			flash('Error: No puede eliminarse la unidad de medida porque esta siendo usada por articulos','danger');
			return redirect()->back();
		}else{
			$unidad->delete();
			flash('Unidad de medida eliminada exitosamente','success');
		    return redirect()->route('unidad.index');
    }
	
}
}

resources/views/unidadmedida/create.blade.php
@extends('layouts.template')

@section('content')

<div class="col-md-offset-2">
    <h3>Nueva Unidad de medida</h3>
</div>
<hr/>
      
{!! Form::open(array('route' => 'unidad.store','class' => 'form-horizontal','method' => 'post')) !!}               
        
        <div class="form-group">
            {!!Form::label('Unidad de medida', 'Unidad de medida', array('class' =>'control-label col-md-2' )) !!}
			<div class="col-md-7">
                {!!Form::text('nombre_unidadmedida', null, array('placeholder' => 'Gramo,Litro','class' => 'form-control')) !!}
				<div class="error">
					<ul>@foreach($errors->get('nombre_unidadmedida') as $msg)<li>{{$msg}}</li> @endforeach</ul>
				</div>
			</div>
        </div>        
        
		<div class="form-group">
            <div class="col-md-offset-2 col-md-7">
                <button type="submit" class="btn btn-primary">Guardar</button>
				<a href="{{route('unidad.index')}}" class="btn btn-primary">Cancelar</a>
            </div>
		</div>
    
{!! Form::close() !!}

@endsection

resources/views/unidadmedida/delete.blade.php
@extends('layouts.template')

@section('content')

<div class="col-md-offset-1">
    <h3>Eliminar Unidad de medida</h3>
</div>
<hr/>
    @if($unidad)
	 
	    <div class="col-md-offset-1">
	        <h4>Esta seguro que desea eliminar la siguiente unidad de medida?</h4>
	    </div>
        <dl class="dl-horizontal col-md-offset-1"> 
	        <dt>Unidad de medida: </dt> 
		    <dd>{{ $unidad->nombre_unidadmedida}}</dd>			   	   
	    <dl>
	    {!! Form::open(['method' => 'DELETE','route' => ['unidad.destroy', $unidad->id_unidad_medida],'style'=>'display:inline']) !!}
	        <div>
                {!! Form::submit('Eliminar', ['class' => 'btn btn-primary']) !!}
			    <a href="{{ route('unidad.index')}}" class="btn btn-primary">Cancelar</a>
		    </div>
        {!! Form::close() !!}
    @endif
@endsection

resources/views/unidadmedida/details.blade.php
@extends('layouts.template')

@section('content')

<div class="col-md-offset-1">
<h3>Detalle</h3>
</div>
<hr/>
 @if($unidad)
	 
     <dl class="dl-horizontal"> 
	    <dt>Unidad de medida: </dt> 
		<dd>{{ $unidad->nombre_unidadmedida}}</dd> 
	 </dl>
	 	 
	<div class="panel panel-info">
	    <div class="panel-heading" role="tab">
			<h4 class="panel-title">
				<strong>Art&iacute;culos que pertenecen a esta unidad de medida</strong>
			</h4>
		</div>
		<div class="panel-body">
				<a href="{{route('articulo.index')}}" data-toggle="modal" class="btn btn-success btn-sm admin" >Ir a administracion de articulos</a>
				<ol>
				    @foreach($unidad->articulo as $art)
					    <li>
					         {{$art->nombre_articulo}}
					    </li>
	                @endforeach
				</ol>
					
	    </div>		    
				
	</div>
	 
	 <div class="col-md-offset-1">
         <a href="{{ route('unidad.index')}}" class="btn btn-primary">Vover a la lista</a>
     </div>
  @endif
 
@endsection

resources/views/unidadmedida/edit.blade.php
@extends('layouts.template')
@section('content')
    
    <div class="col-md-offset-2">
        <h3>Editar</h3>
    </div>
    
    @if($unidad)
	    {!! Form::open(array('route' => ['unidad.update','id_unidad_medida' => $unidad->id_unidad_medida],'class' => 'form-horizontal','method' => 'put')) !!}
           
            <div class="form-group">
                {!! Form::label('Unidad de medida', 'Unidad de medida', array('class' =>'control-label col-md-2' )) !!}
				<div class="col-md-7">
                    {!!Form::text('nombre_unidadmedida', $unidad->nombre_unidadmedida, array('placeholder' => 'Gramo,Litro','class' => 'form-control')) !!}
				<div class="error">
					<ul>@foreach($errors->get('nombre_unidadmedida') as $msg)<li>{{$msg}}</li> @endforeach</ul>
				</div>
				</div>
            </div>        
        
		    <div class="form-group">
                <div class="col-md-offset-2 col-md-7">
                <button type="submit" class="btn btn-primary">Actualizar</button>
				<a href="{{route('unidad.index')}}" class="btn btn-primary">Cancelar</a>
                </div>
		    </div>
			
        {!! Form::close() !!} 
    @endif		
    
@endsection

resources/views/unidadmedida/index.blade.php
@extends('layouts.template')

@section('content')
<div class="encabezado">
    <h3>Unidades de medida</h3> 
</div>

<a href="{{ route('unidad.create')}}" class="btn btn-success"><span class="glyphicon glyphicon-plus"></span>Nuevo</a>
<div class="table-responsive">
    
<table class="table table-hover table-striped table-bordered table-condensed" id="TablaUnidadMedida">
<thead>
    <tr class="success">
        
        <th>Unidad</th>    
	    <th></th>
    </tr>
 </thead>
<tbody>
 
@foreach ($unidades as $unidad)
    <tr>  
        
        <td>{{$unidad->nombre_unidadmedida}}</td>    
	    <td class="col-md-5">
	        <a class="btn btn-default btn-sm" href="{{route('delete_unidad',$unidad->id_unidad_medida)}}"><span class="glyphicon glyphicon-trash" title="Eliminar"></span></a>
	        <a class="btn btn-default btn-sm" href="{{route('unidad.show',$unidad->id_unidad_medida)}}"><span class="glyphicon glyphicon-th-large" title="Detalle"></span></a>
	        <a class="btn btn-default btn-sm" href="{{route('unidad.edit',$unidad->id_unidad_medida)}}"><span class="glyphicon glyphicon-pencil" title="Actualizar"></span></a>
	    </td>   
    </tr>
@endforeach
</tbody>  
</table>
</div>
@endsection

@section('script')
<script type="text/javascript">
  $(document).ready(function(){
  
    $('#TablaUnidadMedida').DataTable(
      {         
          "lengthChange": false,
           "autoWidth": false  
      });
  }); 
</script>
@endsection