app/Http/routes.php
<?php


Route::get('/', function () {
       return view('Auth.login');
   });


	//rutas para usuarios

Route::get('login','UsersController@showLoginForm');
Route::post('login','UsersController@authenticate');
Route::get('logout','UsersController@logout');
Route::get('register','UsersController@getRegister');
Route::post('register','UsersController@postRegister');
Route::get('usuario/create/{id}','UsersController@create');
Route::resource('usuario','UsersController');


Route::group(['middleware'=>['auth','admin_sistema']],function(){
	//ruta para los roles
	Route::resource('roles','RolesController');
    //rutas de usuarios q solo puede acceder el admin
	Route::get('user/{id}',['as'=>'usuario-eliminar','uses'=>'UsersController@mostrar']);
	Route::get('{id}/edit','UsersController@getEdit');
});

//ruta hacia home
Route::get('home', 'HomeController@index');
//rutas para proveedor
Route::get('proveedor/detail/{id}', 'Article\ProviderController@detail');
Route:: resource('proveedor','Article\ProviderController');
//rutas para departamento
Route::resource('departamento', 'Departamento\DepartmentController');
//rutas para especifico
Route::resource('especifico','EspecificoController');
Route::get('especifico/delete/{id}','EspecificoController@delete')->name('yes');
//rutas para unidad de medida
Route::resource('unidad','UnidadMedidaController');
Route::get('unidad/delete/{id_unidad_medida}','UnidadMedidaController@delete')->name('delete_unidad');
//rutas para articulo
Route::resource('articulo','ArticuloController');
Route::get('articulo/delete/{codigoArticulo}','ArticuloController@delete')->name('delete_articulo');
//rutas para ingreso
Route::resource('ingreso','IngresoController');
Route::get('ingreso/delete/{idIngreso}','IngresoController@delete')->name('delete_ingreso');

Route::get('ingreso/addExistencia/{codProducto}/{idPresentacion}','IngresoController@addExistencia')->name('addExistencia');

Route::resource('observacion','ObservacionController');
Route::get('observacion/delete/{idObservacion}','ObservacionController@delete')->name('delete_observacion');


Route::resource('existencia','ExistenciaController');

Route::resource('presentacion','PresentacionController');

//rutas para observacion
Route::resource('observacion','ObservacionController');
Route::get('observacion/delete/{idObservacion}','ObservacionController@delete')->name('delete_observacion');


//requisicion
//ver la requisicion que se esta creando
Route::get('requisicion/crear',[
		'as'=>'requisicion-show',
		'uses'=>'RequisicionController@crear'
	]);
//agregar articulo a la requisicion
Route::get('requisicion/add/{cod}/{cantidad}','RequisicionController@add');

//eliminar articulo de la requisicion
Route::get('requisicion/delete/{cod}',[
		'as'=>'requisicion-delete',
		'uses'=>'RequisicionController@delete'
	]);
//eliminar la requisicion que se esta creando
Route::get('requisicion/trash',[
		'as'=>'requisicion-trash',
		'uses'=>'RequisicionController@trash'
	]);
//actualizar cantidad en articulo de la requisicion
Route::get('requisicion/update/{cod}/{cantidad}','RequisicionController@update');
//almacenar la requisicion
Route::get('requisicion/store','RequisicionController@store');
Route::get('requisicion/listar',['as'=>'requisicion-listar','uses'=>'RequisicionController@index']);

// detalle requisicion
 //para todo el controlador
Route::resource('requisicion/detalle','DetalleRequisicionController');
//aprobar la requisicion (por el administrador financiero)
Route::get('requisicion/detalle/aprobar/{id}','DetalleRequisicionController@aprobar');
//imprimir requisicion
Route::get('requisicion/imprimir/{id}','DetalleRequisicionController@imprimir');
Route::get('requisicion/observacion/{id}',[
	'as'=>'requisicion-observacion',
	'uses'=>'DetalleRequisicionController@observacion'
	]);
//habilitar que los usuarios de departamento envien requisiciones
Route::get('habilitarEnvios',['as'=>'habilitar-envios','uses'=>'RequisicionController@HabilitarEnvio']);
Route::get('gestinarEnvios/{id}',['as'=>'gestionar-envios','uses'=>'RequisicionController@gestionarEnvios']);

app/Models/Especifico.php
<?php

namespace sig\Models;
use sig\Models\Articulo;

use Illuminate\Database\Eloquent\Model;

class Especifico extends Model
{
    protected $table = 'especificos';
	protected $primarykey = 'id';
	//Indica que no se esta usando una llave autoincremental
    protected $fillable = [
	    'id','titulo_especifico','descripcion_epecifico',
	];
	
	public function getEspecificoTitulo(){
		$espTitulo = $this->id.", ".$this->titulo_especifico;
		return $espTitulo;
	}
	//Relacion uno a muchos con articulo
	public function articulo(){
		return $this->hasMany('sig\Models\Articulo','id_especifico');
	}
	
}

resources/views/especifico/create.blade.php
@extends('layouts.template')

@section('content')

<div class="col-md-offset-2">
    <h3>Nuevo Especifico</h3>
</div>
<hr/>      

{!! Form::open(array('route' => 'especifico.store','class' => 'form-horizontal','method' => 'post')) !!}
       
            <div class="form-group">
			    {!!Form::label('Numero', 'Numero', array('class' =>'control-label col-md-2' )) !!}
				<div class="col-md-7">
                    {!!Form::number('numero',null, array('placeholder' => '1234','class' => 'form-control')) !!}
					<div class="error">
					    <ul>@foreach($errors->get('numero') as $msg)<li>{{$msg}}</li> @endforeach</ul>
				    </div>
				</div>
            </div>
                    
            <div class="form-group">
                {!!Form::label('Titulo', 'Titulo', array('class' =>'control-label col-md-2' )) !!}
				<div class="col-md-7">
                    {!!Form::text('titulo', null, array('placeholder' => 'Quimicos','class' => 'form-control')) !!}
					<div class="error">
					    <ul>@foreach($errors->get('titulo') as $msg)<li>{{$msg}}</li> @endforeach</ul>
				    </div>
				</div>
            </div>
        
            <div class="form-group">
                {!!Form::label('Descripcion', 'Descripcion', array('class' =>'control-label col-md-2' )) !!}
				<div class="col-md-7">
                    {!!Form::textarea('descripcion',null,array( 'class' => 'form-control' )) !!}
					<div class="error">
					    <ul>@foreach($errors->get('descripcion') as $msg)<li>{{$msg}}</li> @endforeach</ul>
				    </div>
				</div>
            </div>
			
        <div class="form-group">
            <div class="col-md-offset-2 col-md-7">
                <button type="submit" class="btn btn-primary">Guardar</button>
				<a href="{{ route('especifico.index')}}" class="btn btn-primary">Cancelar</a>
            </div>
		</div>
    
{!! Form::close() !!}

@endsection

resources/views/especifico/delete.blade.php
@extends('layouts.template')

@section('content')

<div class="col-md-offset-1">
    <h3>Eliminar Especifico</h3>
</div>
<hr/>
 @if($especifico)
	 <div class="col-md-offset-1">
	     <h4>Esta seguro que desea eliminar el siguiente especifico?</h4>
	 </div>
     <dl class="dl-horizontal"> 
	     <dt>Codigo: </dt> 
		 <dd>{{ $especifico->id}}</dd> 
		 
		<dt>Titulo: </dt> 
		<dd>{{ $especifico->titulo_especifico }}</dd>
		
	    <dt>Descripcion: </dt> 
		<dd>{{ $especifico->descripcion_epecifico }}</dd>
	 </dl>
	 
	 {!! Form::open(['method' => 'DELETE','route' => ['especifico.destroy', $especifico->id],'style'=>'display:inline']) !!}
	     <div class="col-md-offset-1">
            {!! Form::submit('Delete', ['class' => 'btn btn-primary']) !!}
			<a href="{{ route('especifico.index')}}" class="btn btn-primary">Cancelar</a>
		 </div>
     {!! Form::close() !!}	 
     
 @endif
@endsection

resources/views/especifico/details.blade.php
@extends('layouts.template')

@section('content')

<div class="col-md-offset-1">
    <h3>Detalle</h3>
</div>
<hr/>
 @if($especifico)
	 
    <dl class="dl-horizontal"> 
	    <dt>Numero: </dt> 
		<dd>{{ $especifico->id}}</dd> 
		
		<dt>Titulo: </dt> 
		<dd>{{ $especifico->titulo_especifico }}</dd>
		
	    <dt>Descripcion: </dt> 
		<dd>{{ $especifico->descripcion_epecifico }}</dd>
		
	</dl>
	 	 
	<div class="panel panel-info">
	    <div class="panel-heading" role="tab">
			<h4 class="panel-title">
				<strong>Art&iacute;culos que pertenecen a este especifico</strong>
			</h4>
		</div>
		<div class="panel-body">				
				<ol>
				    @foreach($especifico->articulo as $art)
					    <li>
					         {{$art->nombre_articulo}}
					    </li>
	                @endforeach
				</ol>			
	    </div>					
	</div>
	 
	 <div class="col-md-offset-1">
         <a href="{{ route('especifico.index')}}" class="btn btn-primary">Vover a la lista</a>
     </div>     
  @endif	 
 
@endsection

resources/views/especifico/edit.blade.php
@extends('layouts.template')
@section('content')
    
    <div class="col-md-offset-2">
        <h3>Editar</h3>
    </div>
    <hr/>
    @if($especifico)
	    {!! Form::open(array('route' => ['especifico.update','id' => $especifico->id],'class' => 'form-horizontal','method' => 'put')) !!}
	
	        <div class="form-group">
                {!!Form::label('Especifico', 'Especifico', array('class' =>'control-label col-md-2' )) !!}
				<div class="col-md-7">
                    {!!Form::text('numero', $especifico->id, array('placeholder' => '1234','class' => 'form-control','disabled')) !!}
					<div class="error">
					    <ul>@foreach($errors->get('numero') as $msg)<li>{{$msg}}</li> @endforeach</ul>
				    </div>
				</div>
            </div>
           
            <div class="form-group">
                {!!Form::label('Titulo', 'Titulo', array('class' =>'control-label col-md-2' )) !!}
				<div class="col-md-7">
                    {!!Form::text('titulo', $especifico->titulo_especifico, array('placeholder' => 'Quimicos','class' => 'form-control')) !!}
					<div class="error">
					    <ul>@foreach($errors->get('titulo') as $msg)<li>{{$msg}}</li> @endforeach</ul>
				    </div>
				</div>
            </div>
                      
            <div class="form-group">
                {!!Form::label('Descripcion', 'Descripcion', array('class' =>'control-label col-md-2' )) !!}
				<div class="col-md-7">
                    {!!Form::textarea('descripcion',$especifico->descripcion_epecifico, array('class' => 'form-control')) !!}
					<div class="error">
					    <ul>@foreach($errors->get('descripcion') as $msg)<li>{{$msg}}</li> @endforeach</ul>
				    </div>
				</div>
            </div>
			
           <div class="form-group">
               <div class="col-md-offset-2 col-md-7">
                   <button type="submit" class="btn btn-primary">Actualizar</button>
				   <a href="{{ route('especifico.index')}}" class="btn btn-primary">Cancelar</a>
               </div>
		   </div>

        {!! Form::close() !!}            
    
    @endif
@endsection

resources/views/especifico/index.blade.php
@extends('layouts.template')

@section('content')
<div class="encabezado">
    <h3>Especificos</h3>
</div>

<a href="{{ route('especifico.create')}}" class="btn btn-success"><span class="glyphicon glyphicon-plus"></span>Nuevo</a>

<div class="table-responsive">
<table class="table table-hover table-striped table-bordered table-condensed" id="TablaEspecifico">
<thead>
    <tr class="success">
        <th>Numero</th>
        <th>Titulo</th>
        <th>Descripcion</th>
	    <th></th>
    </tr>
</thead>
<tbody>
 
@foreach ($especificos as $especifico)
    <tr>  
        <td>{{$especifico->id}}</td>
        <td>{{$especifico->titulo_especifico}}</td>
        <td>{{$especifico->descripcion_epecifico}}</td>
	    <td class="col-md-5">
	        <a class="btn btn-default btn-sm" href="{{route('yes',$especifico->id)}}"><span class="glyphicon glyphicon-trash"></span></a>
	        <a class="btn btn-default btn-sm" href="{{route('especifico.show',$especifico->id)}}"><span class="glyphicon glyphicon-th-large"></span></a>
	        <a class="btn btn-default btn-sm" href="{{route('especifico.edit',$especifico->id)}}"><span class="glyphicon glyphicon-pencil"></span></a>
	    </td>         
    </tr>
 @endforeach
</tbody>  
</table>
</div>

@endsection

@section('script')
<script type="text/javascript">
  $(document).ready(function(){
  
    $('#TablaEspecifico').DataTable(
      {         
          "lengthChange": false,
           "autoWidth": false  
      });
  }); 
</script>
@endsection