app/Http/routes.php
<?php


Route::get('/', function () {
       return view('Auth.login');
   });


	//rutas para usuarios

Route::get('login','UsersController@showLoginForm');
Route::post('login','UsersController@authenticate');
Route::get('logout','UsersController@logout');
Route::get('register','UsersController@getRegister');
Route::post('register','UsersController@postRegister');
Route::get('usuario/create/{id}','UsersController@create');
Route::resource('usuario','UsersController');


Route::group(['middleware'=>['auth','admin_sistema']],function(){
	//ruta para los roles
	Route::resource('roles','RolesController');
    //rutas de usuarios q solo puede acceder el admin
	Route::get('user/{id}',['as'=>'usuario-eliminar','uses'=>'UsersController@mostrar']);
	Route::get('{id}/edit','UsersController@getEdit');
});

//ruta hacia home
Route::get('home', 'HomeController@index');
//rutas para proveedor
Route::get('proveedor/detail/{id}', 'Article\ProviderController@detail');
Route:: resource('proveedor','Article\ProviderController');
//rutas para departamento
Route::resource('departamento', 'Departamento\DepartmentController');
//rutas para especifico
Route::resource('especifico','EspecificoController');
Route::get('especifico/delete/{id}','EspecificoController@delete')->name('yes');
//rutas para unidad de medida
Route::resource('unidad','UnidadMedidaController');
Route::get('unidad/delete/{id_unidad_medida}','UnidadMedidaController@delete')->name('delete_unidad');
//rutas para articulo
Route::resource('articulo','ArticuloController');
Route::get('articulo/delete/{codigoArticulo}','ArticuloController@delete')->name('delete_articulo');
//rutas para ingreso
Route::resource('ingreso','IngresoController');
Route::get('ingreso/delete/{idIngreso}','IngresoController@delete')->name('delete_ingreso');

Route::get('ingreso/addExistencia/{codProducto}/{idPresentacion}','IngresoController@addExistencia')->name('addExistencia');

Route::resource('observacion','ObservacionController');
Route::get('observacion/delete/{idObservacion}','ObservacionController@delete')->name('delete_observacion');


Route::resource('existencia','ExistenciaController');

Route::resource('presentacion','PresentacionController');

//rutas para observacion
Route::resource('observacion','ObservacionController');
Route::get('observacion/delete/{idObservacion}','ObservacionController@delete')->name('delete_observacion');


//requisicion
//ver la requisicion que se esta creando
Route::get('requisicion/crear',[
		'as'=>'requisicion-show',
		'uses'=>'RequisicionController@crear'
	]);
//agregar articulo a la requisicion
Route::get('requisicion/add/{cod}/{cantidad}','RequisicionController@add');

//eliminar articulo de la requisicion
Route::get('requisicion/delete/{cod}',[
		'as'=>'requisicion-delete',
		'uses'=>'RequisicionController@delete'
	]);
//eliminar la requisicion que se esta creando
Route::get('requisicion/trash',[
		'as'=>'requisicion-trash',
		'uses'=>'RequisicionController@trash'
	]);
//actualizar cantidad en articulo de la requisicion
Route::get('requisicion/update/{cod}/{cantidad}','RequisicionController@update');
//almacenar la requisicion
Route::get('requisicion/store','RequisicionController@store');
Route::get('requisicion/listar',['as'=>'requisicion-listar','uses'=>'RequisicionController@index']);

// detalle requisicion
 //para todo el controlador
Route::resource('requisicion/detalle','DetalleRequisicionController');
//aprobar la requisicion (por el administrador financiero)
Route::get('requisicion/detalle/aprobar/{id}','DetalleRequisicionController@aprobar');
//imprimir requisicion
Route::get('requisicion/imprimir/{id}','DetalleRequisicionController@imprimir');
Route::get('requisicion/observacion/{id}',[
	'as'=>'requisicion-observacion',
	'uses'=>'DetalleRequisicionController@observacion'
	]);
//habilitar que los usuarios de departamento envien requisiciones
Route::get('habilitarEnvios',['as'=>'habilitar-envios','uses'=>'RequisicionController@HabilitarEnvio']);
Route::get('gestinarEnvios/{id}',['as'=>'gestionar-envios','uses'=>'RequisicionController@gestionarEnvios']);

resources/views/presentacion/create.blade.php
@extends('layouts.template')

@section('content')

<div class="col-md-offset-2">
    <h3>Nueva Presentacio</h3>
</div>
<hr/>      

{!! Form::open(array('route' => 'presentacion.store','class' => 'form-horizontal','method' => 'post')) !!}
       
            
                    
            <div class="form-group">
                {!!Form::label('Presentacion', 'Presentacion', array('class' =>'control-label col-md-2' )) !!}
				<div class="col-md-7">
                    {!!Form::text('presentacion', null, array('placeholder' => 'Galon de pintura roja','class' => 'form-control')) !!}
					<div class="error">
					    <ul>@foreach($errors->get('presentacion') as $msg)<li>{{$msg}}</li> @endforeach</ul>
				    </div>
				</div>
            </div>
        
           			
        <div class="form-group">
            <div class="col-md-offset-2 col-md-7">
                <button type="submit" class="btn btn-primary">Guardar</button>
				<a href="{{ route('presentacion.index')}}" class="btn btn-primary">Cancelar</a>
            </div>
		</div>
    
{!! Form::close() !!}

@endsection

resources/views/presentacion/delete.blade.php
@extends('layouts.template')

@section('content')

<div class="col-md-offset-1">
    <h3>Eliminar Presentacion</h3>
</div>
<hr/>
 @if($presentacion)
	 <div class="col-md-offset-1">
	     <h4>Esta seguro que desea eliminar la siguiente presentacion?</h4>
	 </div>
     <dl class="dl-horizontal"> 
	     <dt>Presentacion: </dt> 
		 <dd>{{ $presentacion->presentacion}}</dd> 		 
		
	 </dl>
	 
	 {!! Form::open(['method' => 'DELETE','route' => ['presentacion.destroy', $presentacion->id_pres],'style'=>'display:inline']) !!}
	     <div class="col-md-offset-1">
            {!! Form::submit('Delete', ['class' => 'btn btn-primary']) !!}
			<a href="{{ route('presentacion.index')}}" class="btn btn-primary">Cancelar</a>
		 </div>
     {!! Form::close() !!}	 
     
 @endif
@endsection

resources/views/presentacion/details.blade.php
@extends('layouts.template')

@section('content')

<div class="col-md-offset-1">
    <h3>Detalle</h3>
</div>
<hr/>
 @if($especifico)
	 
     <dl class="dl-horizontal"> 
	    <dt>Numero: </dt> 
		<dd>{{ $especifico->id}}</dd> 
		
		<dt>Titulo: </dt> 
		<dd>{{ $especifico->titulo_especifico }}</dd>
		
	    <dt>Descripcion: </dt> 
		<dd>{{ $especifico->descripcion_epecifico }}</dd>
	 </dl>
	 <div class="alert alert-info">
	 Articulos que pertenecen a este especifico<br/>
     @foreach($especifico->articulo as $art)
	     {{$art->nombre_articulo}}<br/>
	 @endforeach
	 </div>
	 
	 <div class="col-md-offset-1">
         <a href="{{ route('especifico.index')}}" class="btn btn-primary">Vover a la lista</a>
     </div>     
  @endif	 
 
@endsection

resources/views/presentacion/edit.blade.php
@extends('layouts.template')
@section('content')
    
    <div class="col-md-offset-2">
        <h3>Editar</h3>
    </div>
    <hr/>
    @if($presentacion)
	    {!! Form::open(array('route' => ['presentacion.update','id' => $presentacion->id_pres],'class' => 'form-horizontal','method' => 'put')) !!}
	
	                   
            <div class="form-group">
                {!!Form::label('Presentacion', 'Presentacion', array('class' =>'control-label col-md-2' )) !!}
				<div class="col-md-7">
                    {!!Form::text('presentacion', $presentacion->presentacion, array('placeholder' => 'Galon de pintura roja','class' => 'form-control')) !!}
					<div class="error">
					    <ul>@foreach($errors->get('presentacion') as $msg)<li>{{$msg}}</li> @endforeach</ul>
				    </div>
				</div>
            </div>
                      
            			
           <div class="form-group">
               <div class="col-md-offset-2 col-md-7">
                   <button type="submit" class="btn btn-primary">Actualizar</button>
				   <a href="{{ route('especifico.index')}}" class="btn btn-primary">Cancelar</a>
               </div>
		   </div>

        {!! Form::close() !!}            
    
    @endif
@endsection

resources/views/presentacion/index.blade.php
@extends('layouts.template')

@section('content')

<a href="{{ route('presentacion.create')}}" class="btn btn-success"><span class="glyphicon glyphicon-plus"></span>Nuevo</a>

<div class="table-responsive">
<table class="table table-hover table-striped table-bordered table-condensed">
<thead>
    <tr class="success">
        <th>Presentacion</th>
        
	    <th></th>
    </tr>
</thead>
<tbody>
 
@foreach ($presentaciones as $presentacion)
    <tr>  
        
        <td>{{$presentacion->presentacion}}</td>
        
	    <td class="col-md-5">
	        <a class="btn btn-default btn-sm" href="{{route('delete_presentacion',$presentacion->id_pres)}}"><span class="glyphicon glyphicon-trash"></span>Eliminar</a>
	        <a class="btn btn-default btn-sm" href="{{route('presentacion.show',$presentacion->id_pres)}}"><span class="glyphicon glyphicon-th-large"></span>Detalle</a>
	        <a class="btn btn-default btn-sm" href="{{route('presentacion.edit',$presentacion->id_pres)}}"><span class="glyphicon glyphicon-pencil"></span>Actualizar</a>
	    </td>         
    </tr>
 @endforeach
</tbody>  
</table>
</div>

@endsection