app/Http/routes.php
<?php


Route::get('/', function () {
       return view('Auth.login');
   });


	//rutas para usuarios

Route::get('login','UsersController@showLoginForm');
Route::post('login','UsersController@authenticate');
Route::get('logout','UsersController@logout');
Route::get('register','UsersController@getRegister');
Route::post('register','UsersController@postRegister');
Route::get('usuario/create/{id}','UsersController@create');
Route::resource('usuario','UsersController');


Route::group(['middleware'=>['auth','admin_sistema']],function(){
	//ruta para los roles
	Route::resource('roles','RolesController');
    //rutas de usuarios q solo puede acceder el admin
	Route::get('user/{id}',['as'=>'usuario-eliminar','uses'=>'UsersController@mostrar']);
	Route::get('{id}/edit','UsersController@getEdit');
});

//ruta hacia home
Route::get('home', 'HomeController@index');
//rutas para proveedor
Route::get('proveedor/detail/{id}', 'Article\ProviderController@detail');
Route:: resource('proveedor','Article\ProviderController');
//rutas para departamento
Route::resource('departamento', 'Departamento\DepartmentController');
//rutas para especifico
Route::resource('especifico','EspecificoController');
Route::get('especifico/delete/{id}','EspecificoController@delete')->name('yes');
//rutas para unidad de medida
Route::resource('unidad','UnidadMedidaController');
Route::get('unidad/delete/{id_unidad_medida}','UnidadMedidaController@delete')->name('delete_unidad');
//rutas para articulo
Route::resource('articulo','ArticuloController');
Route::get('articulo/delete/{codigoArticulo}','ArticuloController@delete')->name('delete_articulo');
//rutas para ingreso
Route::resource('ingreso','IngresoController');
Route::get('ingreso/delete/{idIngreso}','IngresoController@delete')->name('delete_ingreso');

Route::get('ingreso/addExistencia/{codProducto}/{idPresentacion}','IngresoController@addExistencia')->name('addExistencia');

Route::resource('observacion','ObservacionController');
Route::get('observacion/delete/{idObservacion}','ObservacionController@delete')->name('delete_observacion');


Route::resource('existencia','ExistenciaController');

Route::resource('presentacion','PresentacionController');

//rutas para observacion
Route::resource('observacion','ObservacionController');
Route::get('observacion/delete/{idObservacion}','ObservacionController@delete')->name('delete_observacion');


//requisicion
//ver la requisicion que se esta creando
Route::get('requisicion/crear',[
		'as'=>'requisicion-show',
		'uses'=>'RequisicionController@crear'
	]);
//agregar articulo a la requisicion
Route::get('requisicion/add/{cod}/{cantidad}','RequisicionController@add');

//eliminar articulo de la requisicion
Route::get('requisicion/delete/{cod}',[
		'as'=>'requisicion-delete',
		'uses'=>'RequisicionController@delete'
	]);
//eliminar la requisicion que se esta creando
Route::get('requisicion/trash',[
		'as'=>'requisicion-trash',
		'uses'=>'RequisicionController@trash'
	]);
//actualizar cantidad en articulo de la requisicion
Route::get('requisicion/update/{cod}/{cantidad}','RequisicionController@update');
//almacenar la requisicion
Route::get('requisicion/store','RequisicionController@store');
Route::get('requisicion/listar',['as'=>'requisicion-listar','uses'=>'RequisicionController@index']);

// detalle requisicion
 //para todo el controlador
Route::resource('requisicion/detalle','DetalleRequisicionController');
//aprobar la requisicion (por el administrador financiero)
Route::get('requisicion/detalle/aprobar/{id}','DetalleRequisicionController@aprobar');
//imprimir requisicion
Route::get('requisicion/imprimir/{id}','DetalleRequisicionController@imprimir');
Route::get('requisicion/observacion/{id}',[
	'as'=>'requisicion-observacion',
	'uses'=>'DetalleRequisicionController@observacion'
	]);
//habilitar que los usuarios de departamento envien requisiciones
Route::get('habilitarEnvios',['as'=>'habilitar-envios','uses'=>'RequisicionController@HabilitarEnvio']);
Route::get('gestinarEnvios/{id}',['as'=>'gestionar-envios','uses'=>'RequisicionController@gestionarEnvios']);

app/Models/Requisicion.php
<?php

namespace sig\Models;

use Illuminate\Database\Eloquent\Model;

class Requisicion extends Model
{
    protected $table = 'requisicions';
    protected $primaryKey = 'id';
 

    protected $fillable=[
    	'id' ,'estado','departamento_id','fecha_solicitud','fecha_entrega','total','observacion','financiero_id','bodega_id',
    ];

      
   public function departamento(){
		return $this->hasOne('sig\Models\Department','id','departamento_id');
	}
    public function bodega(){
        return $this->hasOne('sig\User','id','bodega_id');
    }
    public function financiero(){
        return $this->hasOne('sig\User','id','financiero_id');
    }

	public function detalles(){
    	return $this->hasMany('sig\Models\DetalleRequisicion','requisicion_id');		
	}

}

app/Http/Controllers/RequisicionController.php
<?php

namespace sig\Http\Controllers;

use Illuminate\Http\Request;
use sig\Http\Requests;
use sig\Models\Articulo;
use sig\Models\Requisicion;
use sig\Models\DetalleRequisicion;
use sig\Models\Department;
use Jenssegers\Date\Date;
use sig\Models\CodigoRequisicion;
use Auth;
use DB;

class RequisicionController extends Controller
{
    
  public function __construct()
   {
    if(!\Session::has('requisicion')) 
     
      \Session::put('requisicion',array());

    $this->middleware('auth');
  }      
   
   //funcion para ver la requisicion que se esta creando
   public function crear()
   {
    if(\Auth::User()->departamento['enviar']=='true'){
        $req = Requisicion::whereRaw('estado = ? and departamento_id = ?',array('almacenada',\Auth::User()->departamento_id))->first();
       
        if($req){
            $artuculos = \Session::get('requisicion');
            $total = $this->total();
            return view('Requisicion.crear',['articulos'=>$artuculos,'total'=>$total,'requisicion'=>$req]);
        }
        else{
          $date = Date::now();
          $año = $date->format('Y');
          $inicio = new Date($año.'-1-1');
          $fin= new Date($año.'-12-31');
          $requisiciones =Requisicion::whereBetween('created_at', array($inicio, $fin))->get();
          $codigo = CodigoRequisicion::getCodigo($requisiciones);
          Requisicion::create([
                  'id'=>$codigo,
                  'estado' =>'almacenada',
                  'departamento_id' =>\Auth::User()->departamento_id,                   
                  ]);
          $artuculos = \Session::get('requisicion');
          $total = $this->total();
          return view('Requisicion.crear',['articulos'=>$artuculos,'total'=>$total,'requisicion'=>$req]);
        }
    }
    else{
      flash('No es periodo de envío de Requisiciones','danger');
      return back();
    }
        
   
   }

   public function add($cod, $cantidad){

        $articulo= Articulo::where('codigo_articulo',$cod)->first();
        $articulo->cantidad = $cantidad;
        $req = \Session::get('requisicion');
        $req[$articulo->codigo_articulo]=$articulo;
        \Session::put('requisicion',$req);

      return redirect()->route('requisicion-show');
   }

   //funcion para eliminar articulos de la lista
    public function delete($cod)
    {
       $req = \Session::get('requisicion');
       unset($req[$cod]);
       \Session::put('requisicion',$req);
       return redirect()->route('requisicion-show');
    }
    //funcion para vaciar la variable de session requisicion
    public function trash()
    {
      \Session::forget('requisicion');
      return redirect('home');
    }

    //funcion para calcular el total
    private function total()
    {
        $req= \Session::get('requisicion');
        $total = 0 ;
        foreach ($req as $r) {
          $total += $r->precio_unitario*$r->cantidad;
        }
        return $total;
    }

   
    public function create()
    {
      //
    }

   
    public function store()
    {    
     
      if(\Session::has('requisicion') and !empty(\Session::get('requisicion')))
      {
              $requisicion = \Session::get('requisicion');
              $total = $this->total();
             //obtener requisicion
            $req = Requisicion::where(['estado'=>'almacenada','departamento_id'=>\Auth::User()->departamento_id])->first();            
             //guardamos cada registro de articulos a pedir
            foreach ($requisicion as $r) {
               DetalleRequisicion::create([                
                         'cantidad_solicitada'=>$r->cantidad,
                         'precio'=>$r->precio_unitario,
                         'requisicion_id'=>$req->id,
                         'articulo_id'=>$r->codigo_articulo,
                        ]);
            }
            //actualizar requisicion
            $req->update([
                    'estado' => 'enviada',                    
                    'fecha_solicitud' =>Date::now(),            
                    ]); 
            //eliminamos la variable de sesion
             \Session::forget('requisicion'); 
            return redirect('home');
      }
      else{
        flash('No ha ingresado ningun articulo','danger');
        return back();
      }    

     
    } // fin de almacenar(store) la requisicion y sus detalles

    
    public function show($id)
    {
       //
    }

   
    public function edit($id)
    {
        //
    }

  
    public function update($cod, $cantidad)
    {
       $req = \Session::get('requisicion');
       $req[$cod]->cantidad=$cantidad;
       \Session::put('requisicion',$req);

       return redirect()->route('requisicion-show');
    }

   
   
    public function destroy($id)
    {
        //
    }
    //mostrar todas las requisiciones
     public function index()
    {
      if(Auth::User()->perfil_id==4)       
        {
          $requisicion = DB::table('requisicions')->where([['estado','!=','almacenada'],['departamento_id','=',Auth::User()->departamento_id]])->get();
          return view('Requisicion.departamento_lista',['requisicion'=>$requisicion]);
        }
        else
        {
          if(Auth::User()->perfil_id==3){
              $requisiciones = Requisicion::where('estado','=','actualizada')->get();
          }
          else{
              $requisiciones = Requisicion::where('estado','!=','almacenada')->get();             
          }
          return view('Requisicion.index',['requisicion'=>$requisiciones]);         
        }           

    }
    public function HabilitarEnvio(){
       $departamentos = Department::orderBy('name','asc')->get();
      return view('Requisicion.habilitar_envio_panel',['departamentos'=>$departamentos]);
    }

    public function gestionarEnvios($id){
      if($id==-7){
        $departamentos = Department::all();
        foreach ($departamentos as $d) {
          $d->update([
            'enviar' => 'true',                       
          ]);           
        }
      }
      else
      {
        if($id==-9){
          $departamentos = Department::all();
            foreach ($departamentos as $d) {
              $d->update([
                'enviar' => 'false',                       
              ]);           
            }
        }
        else
        {
          $departamento = Department::where('id',$id)->first();
          if($departamento->enviar=='true')
          {
            $departamento->update([
              'enviar' => 'false',                       
            ]);
          }
          else{
             $departamento->update([
              'enviar' => 'true',                       
            ]);
          }                      
          
        }  
      }
      return back();
     
    }
}

resources/views/Requisicion/actualizar.blade.php
@extends('layouts.template')

@section('content')
 <h3>Departamento : {{$requisicion->departamento['name']}}</h3>
<a href="javascript:window.history.back();" class="btn btn-primary">Regresar</a>
<a href="{{route('requisicion-observacion',$requisicion->id)}}" class="btn btn-primary">Observaciones</a>
<a href="{{url('requisicion/detalle/aprobar',$requisicion->id)}}" class="btn btn-primary">Aprobar</a>
<div class="panel-body table-responsive ">
 
<table class="table table-hover table-striped table-bordered table-condensed" id="TablaDetalleRequesicion">
<thead>
    <tr>
        <th>Codigo</th>
        <th>Nombre del Articulo</th>        
        <th>Unidad de Medida</th>
        <th>Cant Solicitada</th> 
        <th>Cant Aprobada</th>
        <th>Precio</th>             
    </tr>
 </thead>
<tbody>
 
@foreach ($detalle as $d) 

    <tr>  
        <td>{{$d->articulo['codigo_articulo']}}</td>
        <td>{{$d->articulo['nombre_articulo']}}</td>
        <td>{{$d->articulo['unidad']['nombre_unidadmedida']}}</td>
        <td>{{$d->cantidad_solicitada}}</td>     
        <td>
         {!!Form::model($detalle,['route'=>['requisicion.detalle.update',$d->id],'method'=>'patch'])!!}
            <input 
                type="number" 
                min="1" 
                max="1000" 
                name="cantidad"                
                value="{{$d->cantidad_entregada}}" 
            >
            <button type="submit" class="btn btn-warning"><i class="glyphicon glyphicon-refresh"></i></button>
            
                  
          {!!Form::close()!!}
        </td>
        <td>{{$d->articulo['precio_unitario']}}</td>
               
   
    </tr>
  
@endforeach
</tbody>  
</table>
</div>
     
@endsection

@section('script')
<script type="text/javascript">
  $(document).ready(function(){
  
    $("#TablaDetalleRequesicion").DataTable(
      {
        "lengthChange": false,
        "searching": false,
        "info": false,
      });
  });  


</script>
@endsection

resources/views/Requisicion/agregar.blade.php
@extends('layouts.template')

@section('content')

<a href="javascript:window.history.back();" class="btn btn-primary">Cancelar</a>
<div class="panel-body table-responsive ">

<table class="table table-hover table-striped table-bordered table-condensed" id="TablaExistencia">
<thead>
    <tr>
        <th>Codigo</th>
        <th>Nombre del Articulo</th>       
        <th>Unidad de Medida</th>
        <th>Cantidad</th> 
        <th>Precio</th>             
      <th></th>
    </tr>
 </thead>
<tbody>
 
@foreach ($articulos as $a) 

    <tr>  
        <td>{{$a->codigo_articulo}}</td>
        <td>{{$a->nombre_articulo}}</td>        
        <td>{{$a->unidad['nombre_unidadmedida']}}</td>
        <td>
          <input 
              type="number" 
              min="1" 
              max="1000" 
              name="cantidad"
              id="{{$a->codigo_articulo}}" 
          >
        </td>
        <td>{{$a->precio_unitario}}</td>
               
      <td >
          <a 
            class="btn btn-default btn-sm" 
            href="#"
            onClick='agregarArticulo("{{$a->codigo_articulo}}")'         
             
          >           
            <span class="glyphicon glyphicon-plus" title="Agregar">              
            </span>
          </a>
          
      </td>   
    </tr>
  
@endforeach
</tbody>  
</table>
</div>
     
@endsection

@section('script')
<script type="text/javascript">
  $(document).ready(function(){
  
    $("#TablaExistencia").DataTable(
      {
         "lengthChange": false
      });
  });  


var agregarArticulo= function(id){ 
 
  var cantidad = $("#"+id).val(); 
  if(cantidad==""||cantidad>1000||cantidad<1)
  {
    alert("Debe ingresar un valor valido a cantidad");
  }
  else
  {
    window.location.href = "{{url('requisicion/add')}}/"+id +"/" + cantidad; 
  }  
 
}
</script>
@endsection

resources/views/Requisicion/bodega_ver.blade.php
@extends('layouts.template')

@section('content')
 <h3>Departamento : {{$requisicion->departamento['name']}}</h3>
<a href="javascript:window.history.back();" class="btn btn-primary">Regresar</a>
 
<table class="table table-hover table-striped table-bordered table-condensed" id="TablaDetalleRequesicion">
<thead>
    <tr>
        <th>Codigo</th>
        <th>Nombre del Articulo</th>        
        <th>Unidad de Medida</th>
        <th>Cant Solicitada</th> 
        <th>Cant Aprobada</th>
        <th>Precio</th>             
    </tr>
 </thead>
<tbody>
 
@foreach ($detalle as $d) 

    <tr>  
        <td>{{$d->articulo['codigo_articulo']}}</td>
        <td>{{$d->articulo['nombre_articulo']}}</td>
        <td>{{$d->articulo['unidad']['nombre_unidadmedida']}}</td>
        <td>{{$d->cantidad_solicitada}}</td>     
        <td>{{$d->cantidad_entregada}}</td>
       <td>{{number_format($d->articulo['precio_unitario'],2,'.','')}}</td>
               
   
    </tr>
  
@endforeach
</tbody>  
</table>
</div>
     
@endsection

@section('script')
<script type="text/javascript">
  $(document).ready(function(){
  
    $("#TablaDetalleRequesicion").DataTable(
      {
        "lengthChange": false,
        "searching": false,
        "info": false,
      });
  });  


</script>
@endsection

resources/views/Requisicion/crear.blade.php
@extends('layouts.template')

@section('content')

<div>
	<h4>Departamento : <strong>{{Auth::User()->departamento['name']}}</strong></h4>
	<h4>Jefe del Departamento : <strong>{{Auth::User()->name}}</strong></h4> 

	<div>
           <a href="{{route('requisicion.detalle.index')}}" class="btn btn-success">AgregarArticulo <i class="glyphicon glyphicon-plus"></i></a>
           <a href="{{url('requisicion/store')}}" class="btn btn-success">Enviar Requisicion <i class="glyphicon glyphicon-new-window"></i></a>
           @if ($requisicion)
           <a href="{{route('requisicion-observacion',$requisicion->id)}}" class="btn btn-success">Observaciones</a>
           @endif
           <a href="{{route('requisicion-trash')}}" class="btn btn-default">Desechar</a>
    </div>    
</div>

<div class="panel-body table-responsive ">

<table class="table table-hover table-striped table-bordered table-condensed" id="TablaRequisicion">
<thead>
    <tr>
        <th>Codigo</th>
        <th>Nombre del Articulo</th>          
        <th>Unidad de Medida</th>
        <th>Cantidad</th> 
        <th>Precio</th> 
        <th>SubTotal</th>     
        <th></th>
    </tr>
 </thead>
<tbody>
 
@foreach ($articulos as $a) 

    <tr>  
        <td>{{$a->codigo_articulo}}</td>
        <td>{{$a->nombre_articulo}}</td>       
        <td>{{$a->unidad['nombre_unidadmedida']}}</td>
        <td>
          <input 
              type="number" 
              min="1" 
              max="1000" 
              name="cantidad"
              id="articulo_{{$a->codigo_articulo}}"
              value="{{$a->cantidad}}"
           >
              <a href="#" class="btn btn-warning"
              	 onClick='actualizarCantidad("{{$a->codigo_articulo}}")' 
              >
              	<i class="glyphicon glyphicon-refresh"></i>
              </a> 
          
        </td>
        <td>{{$a->precio_unitario}}</td>
        <td>{{$a->precio_unitario*$a->cantidad}}</td> 
        <td>
        	<a href="{{route('requisicion-delete',$a->codigo_articulo)}}" class="btn btn-danger">
        	    <i class="glyphicon glyphicon-remove"></i>
        	</a>
        </td>
    </tr>
  
@endforeach
</tbody>  
</table>

	<h3>
		<span class="label label-default col-md-offset-5">
			Total :  $ {{number_format($total,2)}}
		</span>
	</h3>
</div>

@endsection

@section('script')
<script type="text/javascript">
  $(document).ready(function(){
  
    $("#TablaRequisicion").DataTable(
      {
          "paging": true,
          "lengthChange": false,
          "searching": false,
          "ordering": true,
          "info": false,
          "autoWidth": true
      });
  });  


var actualizarCantidad= function(id){ 
  var cantidad = $("#articulo_"+id).val(); 
  if(cantidad==""||cantidad>1000||cantidad<1)
  {
    alert("Debe ingresar un valor valido a cantidad");
  }
  else
  {
    window.location.href = "{{url('requisicion/update')}}/"+id +"/" + cantidad; 
  }  
 
}
</script>
@endsection

resources/views/Requisicion/departamento_lista.blade.php
@extends('layouts.template')

@section('content')

<div class="panel-body table-responsive ">

<table class="table table-hover table-striped table-bordered table-condensed" id="TablaRequisiciones">
<thead>
    <tr>    
        <th>Fecha de Solicitud</th>  
        <th>Estado</th>         
        <th></th>
    </tr>
 </thead>
<tbody>
 
@foreach ($requisicion as $r) 

    <tr>
        <td>{{$r->fecha_solicitud}}</td>  
        <td>{{$r->estado}}</td>     
        <td>
          <a class="btn btn-default btn-sm" title="detalles" href="{{route('requisicion.detalle.edit',$r->id)}}"><span class="glyphicon glyphicon-th-large "></span></a>
        </td>
    </tr>
  
@endforeach
</tbody>  
</table>


</div>

@endsection

@section('script')
<script type="text/javascript">
  $(document).ready(function(){
  
    $("#TablaRequisiciones").DataTable(
      {
          "paging": true,
          "lengthChange": false,
          "searching": false,
          "ordering": true,
          "info": false,
          "autoWidth": true
      });
  });  


</script>
@endsection

resources/views/Requisicion/departamento_ver.blade.php
@extends('layouts.template')

@section('content')
 <h3>Departamento : {{$requisicion->departamento['name']}}</h3>
<a href="javascript:window.history.back();" class="btn btn-primary">Regresar</a>

<div class="panel-body table-responsive ">
 
<table class="table table-hover table-striped table-bordered table-condensed" id="TablaDetalleRequesicion">
<thead>
    <tr>
        <th>Codigo</th>
        <th>Nombre del Articulo</th>        
        <th>Unidad de Medida</th>
        <th>Cant Solicitada</th> 
        <th>Cant Aprobada</th>
        <th>Precio</th>             
    </tr>
 </thead>
<tbody>
 
@foreach ($detalle as $d) 

    <tr>  
        <td>{{$d->articulo['codigo_articulo']}}</td>
        <td>{{$d->articulo['nombre_articulo']}}</td>
        <td>{{$d->articulo['unidad']['nombre_unidadmedida']}}</td>
        <td>{{$d->cantidad_solicitada}}</td>     
        <td>{{$d->cantidad_entregada}}</td>
        <td>{{number_format($d->articulo['precio_unitario'],2,'.','')}}</td>
               
   
    </tr>
  
@endforeach
</tbody>  
</table>
</div>
     
@endsection

@section('script')
<script type="text/javascript">
  $(document).ready(function(){
  
    $("#TablaDetalleRequesicion").DataTable(
      {
        "lengthChange": false,
        "searching": false,
        "info": false,
      });
  });  


</script>
@endsection

resources/views/Requisicion/financiero_lista.blade.php
@extends('layouts.template')

@section('content')

<div class="panel-body table-responsive ">

<table class="table table-hover table-striped table-bordered table-condensed" id="TablaRequisiciones">
<thead>
    <tr>    
        <th>Fecha de Solicitud</th>  
        <th>Estado</th>         
        <th></th>
    </tr>
 </thead>
<tbody>
 
@foreach ($requisicion as $r) 

    <tr>
        <td>{{$r->fecha_solicitud}}</td>  
        <td>{{$r->estado}}</td>     
        <td>
          <a class="btn btn-default btn-sm" title="editar" href="{{route('requisicion.detalle.edit',$r->id)}}"><span class="glyphicon glyphicon-th-large "></span></a>
        </td>
    </tr>
  
@endforeach
</tbody>  
</table>


</div>

@endsection

@section('script')
<script type="text/javascript">
  $(document).ready(function(){
  
    $("#TablaRequisiciones").DataTable(
      {
          "paging": true,
          "lengthChange": false,
          "searching": false,
          "ordering": true,
          "info": false,
          "autoWidth": true
      });
  });  


</script>
@endsection

resources/views/Requisicion/financiero_ver.blade.php
@extends('layouts.template')

@section('content')
 <h3>Departamento : {{$requisicion->departamento['name']}}</h3>
<a href="javascript:window.history.back();" class="btn btn-primary">Regresar</a>
<a href="{{url('requisicion/detalle/aprobar',$requisicion->id)}}" class="btn btn-primary">Aprobar</a>
<div class="panel-body table-responsive ">
 
<table class="table table-hover table-striped table-bordered table-condensed" id="TablaDetalleRequesicion">
<thead>
    <tr>
        <th>Codigo</th>
        <th>Nombre del Articulo</th>        
        <th>Unidad de Medida</th>
        <th>Cant Solicitada</th> 
        <th>Cant Aprobada</th>
        <th>Precio</th>             
    </tr>
 </thead>
<tbody>
 
@foreach ($detalle as $d) 

    <tr>  
        <td>{{$d->articulo['codigo_articulo']}}</td>
        <td>{{$d->articulo['nombre_articulo']}}</td>
        <td>{{$d->articulo['unidad']['nombre_unidadmedida']}}</td>
        <td>{{$d->cantidad_solicitada}}</td>     
        <td>{{$d->cantidad_entregada}}</td>
        <td>{{number_format($d->articulo['precio_unitario'],2,'.','')}}</td>
               
   
    </tr>
  
@endforeach
</tbody>  
</table>
</div>
     
@endsection

@section('script')
<script type="text/javascript">
  $(document).ready(function(){
  
    $("#TablaDetalleRequesicion").DataTable(
      {
        "lengthChange": false,
        "searching": false,
        "info": false,
      });
  });  


</script>
@endsection

resources/views/Requisicion/index.blade.php
@extends('layouts.template')

@section('content')
<div class="encabezado">
    <h3>Requisiciones</h3>
</div>
<div class="panel-body table-responsive ">

<table class="table table-hover table-striped table-bordered table-condensed" id="TablaRequisiciones">
<thead>
    <tr>
        <th>Numero</th>        
        <th>Departamento</th>  
        <th>Fecha de Solicitud</th>  
        <th>Estado</th>         
        <th></th>
    </tr>
 </thead>
<tbody>
 
@foreach ($requisicion as $r) 

    <tr>  
        <td>{{$r->id}}</td>
        <td>{{$r->departamento['name']}}</td>
        <td>{{$r->fecha_solicitud}}</td>  
        <td>{{$r->estado}}</td>     
        <td>                
         <a class="btn btn-default btn-sm" title="detalles" href="{{route('requisicion.detalle.show',$r->id)}}"><span class="glyphicon glyphicon-th-large "></span></a>
         @if($r->estado == 'aprobada') 
         <a class="btn btn-default btn-sm" title="imprimir" href="{{url('requisicion/imprimir',$r->id)}}"><span class="glyphicon glyphicon-print "></span></a>
         @else 
          <a class="btn btn-default btn-sm" title="editar" href="{{route('requisicion.detalle.edit',$r->id)}}"><span class="glyphicon glyphicon-pencil "></span></a>
          @endif
        </td>
    </tr>
  
@endforeach
</tbody>  
</table>


</div>

@endsection

@section('script')
<script type="text/javascript">
  $(document).ready(function(){
  
    $("#TablaRequisiciones").DataTable(
      {
          "paging": true,
          "lengthChange": false,
          "searching": true,
          "ordering": true,
          "info": false,
          "autoWidth": true
      });
  });  


</script>
@endsection

resources/views/Requisicion/observaciones.blade.php
@extends('layouts.template')

@section('content')
<h3>Agregar Observaciones a la requisicion</h3>
<h3>Departamento de : {{$requisicion->departamento['name']}}</h3>

<a href="javascript:window.history.back();" class="btn btn-primary">Regresar</a>

<div class="form-horizontal">
    {!!Form::open(['route'=>'requisicion.detalle.store','method'=>'POST'])!!}           
  
      <div class="box-body">             
       <textarea name="observaciones" rows="6" cols="100">{{$requisicion->observacion}}</textarea>
       <input type="hidden" name="id" value="{{$requisicion->id}}">
                  
      </div><!-- /.box-body -->                    
          <div class="col-sm-offset-2">
             
              {!!Form::submit('Aceptar',['name'=>'aceptar','id'=>'aceptar','content'=>'<span>Acpetar</span>','class'=>'btn btn-info'])!!}
             
          </div>   
    {!!Form::close()!!}              
  </div>

     
@endsection

@section('script')
<script type="text/javascript">

</script>
@endsection